#!/bin/sh
set -e

if [ "$1" = "configure" ]; then
    update-alternatives \
        --install /bin/nc nc /usr/bin/ncat 0 \
        --slave /bin/netcat netcat /usr/bin/ncat \
        --slave /usr/share/man/man1/nc.1.gz nc.1.gz \
                /usr/share/man/man1/ncat.1.gz \
        --slave /usr/share/man/man1/netcat.1.gz netcat.1.gz \
                /usr/share/man/man1/ncat.1.gz
fi

#DEBHELPER#
